### ISSUE TITLE
[Android Fast Track Bootcamp] Assignment 1: Ready for Review

### ISSUE THREAD

**Issue by atommarvel** [atommarvel/android-instagram#1]
[Assignment 1](http://courses.codepath.com/courses/android_fast_track/unit/1#!assignment) complete.

Do I need to add an Assignment 1 gif in the README?

/cc @codepathreview @codepath @nidhi1608

**Comment by nidhi1608** [comment]
Yep, that'd be great.

**Comment by atommarvel** [comment]
Updated README according to [requirements](http://courses.codepath.com/courses/android_fast_track/pages/submitting_assignments).

**Comment by codepathreview** [comment]
:+1: Great work, good job getting all required stories done. A few notes after checking out the code:

* Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
* Excellent job on a polished UI
* Good job using recycler view along with ViewHolder pattern.

One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I would encourage you to complete the projects each week with required stories early and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

If you have any particular questions about the assignment in general or on any of the feedback, feel free to reply here or or email us <support@codepath.com>.
