### ISSUE TITLE
Assignment 3 Completed

### ISSUE THREAD

**Issue by atommarvel** [atommarvel/android-instagram#3]
Happy Halloween :jack_o_lantern: 
/cc @codepathreview @codepath @nidhi1608

**Comment by codepathreview** [comment]
Good job finishing all the stories. Some feedback after looking at the code -

* Good job putting a global helper method to retrieve the InstagramClient in Application class
* Good job doing any assignment of subviews to fields in `onViewCreated`. This is because the framework does an automatic null check for you to ensure that your Fragment's view hierarchy has been created and inflated (if using an XML layout file) properly.
* Updating the adapter should be done by calling notifyDataSetChanged instead of creating a new adapter after fetching completes
* It's always a good idea to display an indeterminate or determinate progress bar to the user when potentially long running tasks are happening in the background, especially those that update views. See **[this guide on implementing a ProgressBarView](https://guides.codepath.com/android/Handling-ProgressBars)**.
* Good job putting integer dimension, sp, dp etc to 'dimens.xml'
